### ISSUE TITLE
Ensure that schema is up to date with all fields for participation reports

### ISSUE THREAD

**Issue by afandian** [CrossRef/cayenne#37]
`cayenne.api.v1.schema` contains a schema for the response types. New changes to the API may or may not still be compatible. We should check that everything is still compatible after the Participation Reports work, and make sure there's a regression test.

**Comment by jenniferlin15** [comment]
PREP work is completed and thanks to you and Mike we have tests for all the recent cayenne changes added. Closing ticket.

**Comment by ppolischuk** [comment]
Closing per Jennifer's statement above.
